@Movies.Api_HostAddress = https://localhost:7032

GET {{Movies.Api_HostAddress}}/api/movies

###

POST {{Movies.Api_HostAddress}}/api/movies
Content-Type: application/json

{
  "Title": "The Shawshank Redemption",
  "YearOfRelease": 1994,
  "Genres": [
      "Drama"
  ]
}

###

POST {{Movies.Api_HostAddress}}/api/movies
Content-Type: application/json

{
  "Title": "The Godfather",
  "YearOfRelease": 1972,
  "Genres": [
      "Crime","Drama"
  ]
}

###

POST {{Movies.Api_HostAddress}}/api/movies
Content-Type: application/json

{
  "Title": "Fight Club",
  "YearOfRelease": 2026,
  "Genres": [
      "Crime","Drama"
  ]
}

###

GET {{Movies.Api_HostAddress}}/api/movies/the-godfather-1972

###

PUT {{Movies.Api_HostAddress}}/api/movies/dba917f6-7465-4b2e-987e-9df21cc4c2b9
Content-Type: application/json

{
  "title": "The Godfather",
      "yearOfRelease": 1972,
      "genres": [
        "Crime",
        "Drama"
      ]
}

###

DELETE {{Movies.Api_HostAddress}}/api/movies/583d84e2-772b-4fd3-96fd-c5ddd2e1cb9a

###
