@Movies.Api_HostAddress = https://localhost:7032
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2ZqYWRpMjAxMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQyNDkyNDU4LCJpc3MiOiJNb3ZpZXMuQXBpIiwiYXVkIjoiTW92aWVzLkFwaSJ9.YJDI50UWoUyPguwxkKt0wiLRSs_rYXol7PE_8wSZvGI

GET {{Movies.Api_HostAddress}}/api/movies

###

POST {{Movies.Api_HostAddress}}/api/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "The Electric State",
  "YearOfRelease": 2025,
  "Genres": [
      "Sci-fi",
      "Adventure"
  ]
}

###

POST {{Movies.Api_HostAddress}}/api/movies
Content-Type: application/json

{
  "Title": "The Godfather",
  "YearOfRelease": 1972,
  "Genres": [
      "Crime","Drama"
  ]
}

###

POST {{Movies.Api_HostAddress}}/api/movies
Content-Type: application/json

{
  "Title": "Fight Club",
  "YearOfRelease": 2026,
  "Genres": [
      "Crime","Drama"
  ]
}

###

GET {{Movies.Api_HostAddress}}/api/movies/the-godfather-1972

###

PUT {{Movies.Api_HostAddress}}/api/movies/dba917f6-7465-4b2e-987e-9df21cc4c2b9
Content-Type: application/json

{
  "title": "The Godfather",
      "yearOfRelease": 1972,
      "genres": [
        "Crime",
        "Drama"
      ]
}

###

DELETE {{Movies.Api_HostAddress}}/api/movies/583d84e2-772b-4fd3-96fd-c5ddd2e1cb9a

###

POST {{Movies.Api_HostAddress}}/api/token
Content-Type: application/json

{
  "username": "sfjadi2010",
  "password": "P@ssw0rd1"
}

###
